name: Upload

on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest
    name: Upload files to OSS
    steps:
      - name: Configure environment
        id: config
        run: |
          VERSION=$(echo $GITHUB_REF | sed -e "s/^refs\/tags\/v//")
          echo ::set-output name=version::$VERSION

      - name: Fetch repository
        uses: actions/checkout@v2

      - name: Upload files
        id: ossutil
        uses: geekdada/ossutil-github-action@master
        with:
          ossArgs: 'sync --delete --exclude ".git" ./ oss://dada-oss/github/surge-list/'
          accessKey: ${{ secrets.ALIYUN_ACCESS_KEY }}
          accessSecret: ${{ secrets.ALIYUN_ACCESS_SECRET }}
          endpoint: oss-accelerate.aliyuncs.com

      - name: Output command
        run: echo "${{steps.ossutil.outputs.command}}"

      - name: Telegram Notify
        uses: yanzay/notify-telegram@v0.1.0
        if: always()
        with:
          chat: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          status: ${{ job.status }}
